// Panel HTML — file terpisah agar tidak konflik dengan template literal server.js
module.exports = function getPanelHtml() {
    return [
        '<!DOCTYPE html>',
        '<html lang="id">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width,initial-scale=1">',
        '<title>WA Gateway EVAN13</title>',
        '<style>',
        '*{margin:0;padding:0;box-sizing:border-box}',
        'body{font-family:Segoe UI,sans-serif;background:#0D1B2A;color:#E3F2FD;min-height:100vh}',
        'header{background:#1565C0;padding:18px 24px}',
        'header h1{font-size:20px;color:#fff}',
        'header p{font-size:12px;color:#BBDEFB;margin-top:2px}',
        '.wrap{max-width:860px;margin:0 auto;padding:24px 16px}',
        '.card{background:#152238;border-radius:14px;padding:20px;margin-bottom:16px;border:1px solid #1E3A5F}',
        '.card h2{font-size:14px;color:#42A5F5;margin-bottom:14px;text-transform:uppercase;letter-spacing:1px}',
        'input{width:100%;padding:11px 14px;border-radius:8px;border:1px solid #1E3A5F;background:#0D1B2A;color:#E3F2FD;font-size:14px;outline:none}',
        'input:focus{border-color:#1565C0}',
        '.row{display:flex;gap:10px;margin-top:10px}',
        '.btn{padding:11px 20px;border-radius:8px;border:none;cursor:pointer;font-size:13px;font-weight:bold}',
        '.btn-blue{background:#1565C0;color:#fff}',
        '.btn-red{background:#C62828;color:#fff}',
        '.url-box{background:#0D1B2A;border-radius:8px;padding:12px 14px;font-family:monospace;font-size:13px;color:#42A5F5;word-break:break-all;border:1px solid #1E3A5F;margin-bottom:10px}',
        '.item{background:#0D1B2A;border-radius:8px;padding:12px 14px;display:flex;align-items:center;justify-content:space-between;border:1px solid #1E3A5F;margin-bottom:8px}',
        '.badge{padding:3px 10px;border-radius:20px;font-size:11px;font-weight:bold}',
        '.ok{background:#2E7D32;color:#fff}',
        '.conn{background:#E65100;color:#fff}',
        '.qr{background:#1565C0;color:#fff}',
        '.dis{background:#424242;color:#fff}',
        '.modal{display:none;position:fixed;inset:0;background:rgba(0,0,0,.85);z-index:99;align-items:center;justify-content:center}',
        '.modal.show{display:flex}',
        '.mbox{background:#152238;border-radius:16px;padding:28px;text-align:center;max-width:320px;width:90%}',
        '.mbox h3{color:#42A5F5;margin-bottom:6px}',
        '.mbox p{color:#90CAF9;font-size:12px;margin-bottom:14px}',
        '.mbox img{width:240px;height:240px;background:#fff;border-radius:10px;padding:6px}',
        '.cls{margin-top:12px;display:block;color:#90CAF9;cursor:pointer;font-size:12px}',
        '</style>',
        '</head>',
        '<body>',
        '<header><h1>WA Gateway</h1><p>by EVAN13 - Panel Sender</p></header>',
        '<div class="wrap">',

        '<div class="card">',
        '<h2>URL Server</h2>',
        '<div class="url-box" id="sUrl">Memuat...</div>',
        '<button class="btn btn-blue" onclick="copyUrl()">Copy URL untuk APK</button>',
        '</div>',

        '<div class="card">',
        '<h2>Tambah Sender</h2>',
        '<input type="tel" id="num" placeholder="Nomor sender: 6281234567890"/>',
        '<p style="color:#90CAF9;font-size:11px;margin-top:6px">Format 62xxx tanpa + atau spasi</p>',
        '<div class="row"><button class="btn btn-blue" onclick="addSender()">Tambah dan Scan QR</button></div>',
        '</div>',

        '<div class="card">',
        '<h2>Daftar Sender</h2>',
        '<div id="list"><p style="color:#546E7A;font-size:13px">Belum ada sender</p></div>',
        '</div>',

        '</div>',

        '<div class="modal" id="modal">',
        '<div class="mbox">',
        '<h3>Scan QR Code</h3>',
        '<p>WA - Perangkat Tertaut - Tautkan Perangkat</p>',
        '<img id="qrImg" src="" alt="QR"/>',
        '<span class="cls" onclick="closeModal()">Tutup</span>',
        '</div>',
        '</div>',

        '<script>',
        'document.getElementById("sUrl").textContent = location.origin;',
        'function copyUrl(){navigator.clipboard.writeText(location.origin);alert("URL disalin!")}',

        'async function addSender(){',
        '  var n=document.getElementById("num").value.trim();',
        '  if(!n){alert("Masukkan nomor!");return}',
        '  var r=await fetch("/api/sender/add",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({number:n})});',
        '  var d=await r.json();',
        '  document.getElementById("num").value="";',
        '  load();',
        '  var t=0;',
        '  var iv=setInterval(async function(){',
        '    t++;',
        '    var qr=await fetch("/api/sender/qr/"+d.number);',
        '    if(qr.ok){var q=await qr.json();showQr(q.qr,d.number);clearInterval(iv)}',
        '    if(t>12)clearInterval(iv);',
        '  },3000);',
        '}',

        'function showQr(src,num){',
        '  document.getElementById("qrImg").src=src;',
        '  document.getElementById("modal").classList.add("show");',
        '  var iv=setInterval(async function(){',
        '    var r=await fetch("/api/status");',
        '    var d=await r.json();',
        '    var s=d.senders.find(function(x){return x.number===num});',
        '    if(s&&s.status==="connected"){closeModal();load();clearInterval(iv)}',
        '  },3000);',
        '}',

        'function closeModal(){document.getElementById("modal").classList.remove("show")}',

        'async function showQrBtn(num){',
        '  var r=await fetch("/api/sender/qr/"+num);',
        '  if(!r.ok){alert("QR tidak tersedia");return}',
        '  var d=await r.json();showQr(d.qr,num);',
        '}',

        'async function del(num){',
        '  if(!confirm("Hapus sender "+num+"?"))return;',
        '  await fetch("/api/sender/"+num,{method:"DELETE"});load();',
        '}',

        'function badge(s){',
        '  var m={connected:["Terhubung","ok"],connecting:["Connecting","conn"],qr:["Scan QR","qr"],disconnected:["Disconnect","dis"]};',
        '  var lb=m[s]||["Unknown","dis"];',
        '  return "<span class=\\"badge "+lb[1]+"\\">"+lb[0]+"</span>";',
        '}',

        'async function load(){',
        '  var r=await fetch("/api/sender/list");',
        '  var d=await r.json();',
        '  var el=document.getElementById("list");',
        '  if(!d.senders.length){el.innerHTML="<p style=\\"color:#546E7A;font-size:13px\\">Belum ada sender</p>";return}',
        '  var html="";',
        '  for(var i=0;i<d.senders.length;i++){',
        '    var s=d.senders[i];',
        '    html+="<div class=\\"item\\">";',
        '    html+="<span style=\\"font-size:14px;font-weight:bold\\">"+s.number+"</span>";',
        '    html+="<div style=\\"display:flex;gap:8px;align-items:center\\">";',
        '    html+=badge(s.status);',
        '    if(s.hasQr) html+="<button class=\\"btn btn-blue\\" style=\\"padding:5px 10px;font-size:11px\\" onclick=\\"showQrBtn(\'"+s.number+"\')\\" >QR</button>";',
        '    html+="<button class=\\"btn btn-red\\" style=\\"padding:5px 10px;font-size:11px\\" onclick=\\"del(\'"+s.number+"\')\\" >Hapus</button>";',
        '    html+="</div></div>";',
        '  }',
        '  el.innerHTML=html;',
        '}',

        'load();setInterval(load,5000);',
        '</script>',
        '</body>',
        '</html>'
    ].join('\n');
};
